public with sharing class ARBase //implements ActiveRecordBase.Translator
{/*
		static public String tableNameFromInstance( ActiveRecordBase instance )
		{
			if (instance instanceof MyModel)
				return 'My_SObject__c';
			
			// TODO: throw exception instead
			return null;
		}
		
		static public ActiveRecordBase instanceFromTableName( String tableName )
		{
			if ('My_SObject__c' == tableName)
				return new MyModel();
				
			// TODO: throw exception instead
			return null;
		}
*/
}