@isTest
private class TestActiveRecordBase {
/*
    static testMethod void myUnitTest() {
        ActiveRecordBase arb = new ActiveRecordBase();
        
        String myFieldName = 'TestFieldName';
        
        System.assertEquals( myFieldName, arb.get('TestFieldName') );
    }
    
    
    static testMethod void testTrue()
    {
    	
    	ActiveRecordBase.setValue();
    	System.assertEquals(true, ActiveRecordBase.isTrue());
    	System.assertEquals(true, ActiveRecordBase.value);
    	
    }
    
    static testMethod void testFalse()
    {
    	
    	System.assertEquals(false, ActiveRecordBase.isTrue());
    	System.assertEquals(false, ActiveRecordBase.value);
    	    	
    }
  */  
}