@isTest
private class TestScopeModel
{/*
	static testMethod void testGetRecord()
	{
		final String TEST_NAME = 'Test Scope';
		
		ScopeModel model = new ScopeModel();
		model.name = TEST_NAME;
		
		Test.startTest();
			Scope__c record = model.getRecord();
		Test.stopTest();
		
		System.assertNotEquals( null, record, 'The model should return a record.' );
		System.assertEquals( TEST_NAME, record.Name, 'The Name should be populated.' );
	}
	
	static testMethod void testAddFeature()
	{
		ScopeModel model = new ScopeModel();
		
		Test.startTest();
			model.addFeature();
		Test.stopTest();
		
		System.assertEquals( 1, model.features.size(), 'The model should have a single feature.' );
	}*/
}